import type { Category, DailyLocation, InstagramPost, Product, SiteSettings } from "@/lib/types";
import { todayInStore } from "@/lib/format";

/**
 * Built-in catalogue used whenever Supabase is not connected, so the site is complete
 * out of the box. Photos are Unsplash stand-ins (see public/images/lookbook/CREDITS.md).
 * Prices and hours are realistic defaults the owner should confirm. Phone, WhatsApp
 * and street address are never invented: they must come from the owner.
 */

const img = (name: string) => `/images/lookbook/${name}.jpg`;

const allDays = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"];

export const defaultSettings: SiteSettings = {
  business_name: "Geeta Fashion Hub",
  tagline: "Traditional Elegance, Made Just for You.",
  whatsapp_number: process.env.NEXT_PUBLIC_WHATSAPP_NUMBER ?? null,
  phone: process.env.NEXT_PUBLIC_PHONE ?? null,
  email: null,
  address_line: null,
  locality: null,
  city: null,
  state: null,
  postal_code: null,
  country: "IN",
  maps_url: "https://share.google/QsvLeklDoI0dHvXVS",
  maps_embed_url: null,
  latitude: null,
  longitude: null,
  instagram_url: "https://www.instagram.com/geetafashionhub722/",
  facebook_url: null,
  youtube_url: null,
  business_hours: allDays.map((day) => ({ day, open: "10:30", close: "20:30", closed: false })),
  hours_note: "Timings may change on festival days. Check today's location before you visit.",
  service_areas: [],
  about_text: null,
  hero_image_url: img("hero-brides"),
  hero_video_url: null,
  default_whatsapp_message: null,
  instagram_mode: "manual",
  instagram_post_limit: 8,
};

const cat = (name: string, slug: string, sort_order: number, description: string, image: string): Category => ({
  id: `demo-${slug}`,
  name,
  slug,
  description,
  intro: null,
  image_url: img(image),
  sort_order,
  is_active: true,
  seo_title: null,
  seo_description: null,
});

export const demoCategories: Category[] = [
  cat("Blouses", "blouses", 10, "Ready and made-to-measure blouses for sarees and lehengas.", "turquoise-zari-blouse"),
  cat("Antique Blouses", "antique-blouses", 20, "Antique zari, temple and heritage-finish designer blouses.", "navy-velvet-zardozi-blouse"),
  cat("Custom Blouses", "custom-blouses", 30, "Blouses stitched to your measurements and design.", "red-silk-blouse-back"),
  cat("Chaniya Choli", "chaniya-choli", 40, "Traditional and festive chaniya cholis for Navratri, garba and celebrations.", "leheriya-chaniya-choli"),
  cat("Salwar Kameez", "salwar-kameez", 50, "Classic and contemporary salwar kameez suits.", "blue-salwar-suit"),
  cat("Salwar Kurta", "salwar-kurta", 60, "Everyday and occasion kurtas with salwar.", "ivory-kurta-set"),
  cat("Bridal Wear", "bridal-wear", 70, "Bridal lehengas, blouses and cholis for the big day.", "shehzadi-bridal-2"),
  cat("Wedding Collection", "wedding-collection", 80, "Outfits for weddings, receptions, haldi and sangeet.", "mint-wedding-lehenga"),
  cat("Festive Wear", "festive-wear", 90, "Ethnic wear for Diwali, Navratri, Eid and every festival.", "maroon-lehenga-choli"),
  cat("Women's Ethnic Wear", "womens-ethnic-wear", 100, "Traditional Indian clothing for women.", "emerald-ruffle-saree"),
  cat("Girls' Wear", "girls-wear", 110, "Ethnic wear for girls: lehengas, cholis and suits.", "girls-dandiya-chaniya"),
  cat("Kids' Traditional Wear", "kids-traditional-wear", 120, "Traditional outfits for children for festivals and functions.", "girls-silk-lehenga"),
  cat("Custom Designs", "custom-designs", 130, "One-of-a-kind outfits designed with you.", "pearl-cape-saree"),
  cat("Stitching Services", "stitching-services", 140, "Custom stitching, fittings and alterations.", "red-silk-blouse-back"),
];

const byCat = (slug: string) => {
  const c = demoCategories.find((x) => x.slug === slug)!;
  return { category_id: c.id, category: { id: c.id, name: c.name, slug: c.slug } };
};

const product = (p: Partial<Product> & Pick<Product, "name" | "slug">, categorySlug: string): Product => ({
  id: `demo-${p.slug}`,
  subcategory: null,
  short_description: null,
  description: null,
  images: [],
  image_alt: null,
  sizes: [],
  colors: [],
  fabric: null,
  price: null,
  is_customizable: false,
  customization_notes: null,
  stitching_available: false,
  availability: "in_stock",
  is_featured: false,
  featured_order: 0,
  is_visible: true,
  seo_title: null,
  seo_description: null,
  og_image_url: null,
  updated_at: "2026-10-01T00:00:00.000Z",
  ...byCat(categorySlug),
  ...p,
});

const BRIDAL_SIZES = ["Made to measure"];
const BLOUSE_SIZES = ["32", "34", "36", "38", "40", "42", "Custom"];
const SUIT_SIZES = ["S", "M", "L", "XL", "XXL", "Custom"];

export const demoProducts: Product[] = [
  // ── Bridal & wedding ───────────────────────────────────────────────────────
  product(
    {
      name: "Maharani Red Bridal Lehenga",
      slug: "maharani-red-bridal-lehenga",
      subcategory: "Bridal lehenga",
      short_description: "A classic bridal red lehenga with dense zari and sequin work, paired with a matching blouse and net dupatta.",
      description:
        "Our signature bridal lehenga, made for the bride who loves tradition. The flared skirt carries heavy zari, dabka and sequin work across every panel, finished with a scalloped border that catches the light as you walk.\n\nThe blouse is stitched to your measurements, and the neckline, sleeve length and back design can all be chosen during your fitting. A soft net dupatta with an embroidered border completes the look.\n\nPlease allow 3 to 5 weeks for stitching and two fittings.",
      images: [img("red-bridal-lehenga"), img("zari-detail-2"), img("zari-detail-3")],
      image_alt: "Bride in a red lehenga with heavy gold zari embroidery and a red net dupatta",
      sizes: BRIDAL_SIZES,
      colors: ["Bridal Red", "Antique Gold"],
      fabric: "Raw silk with net dupatta",
      price: 48500,
      availability: "made_to_order",
      is_customizable: true,
      customization_notes: "Choose the blouse neckline, sleeve style and back design. The embroidery colour can be matched to your jewellery.",
      stitching_available: true,
    },
    "bridal-wear",
  ),
  product(
    {
      name: "Rani Pink Bridal Lehenga",
      slug: "rani-pink-bridal-lehenga",
      subcategory: "Bridal lehenga",
      short_description: "Rani pink lehenga with gold zardozi, made for day weddings and receptions.",
      description:
        "A joyful rani pink lehenga with gold zardozi motifs and a heavy border. It is light enough for day functions yet grand enough for the wedding itself.\n\nStitched to measure, with your choice of blouse design.",
      images: [img("pink-bridal-lehenga-full"), img("rani-pink-bridal"), img("bridal-portrait-2")],
      image_alt: "Bride in a rani pink lehenga with gold zardozi embroidery and kundan jewellery",
      sizes: BRIDAL_SIZES,
      colors: ["Rani Pink", "Gold"],
      fabric: "Silk blend",
      price: 42000,
      availability: "made_to_order",
      is_customizable: true,
      stitching_available: true,
    },
    "bridal-wear",
  ),
  product(
    {
      name: "Royal Maroon Velvet Lehenga",
      slug: "royal-maroon-velvet-lehenga",
      is_featured: true,
      featured_order: 4,
      subcategory: "Wedding lehenga",
      short_description: "Deep maroon velvet with all-over antique zari, a regal choice for the wedding night.",
      description:
        "Rich maroon velvet embroidered with antique-gold zari in traditional jaal patterns. It has a structured, heavy fall and photographs beautifully under evening light.\n\nIt pairs with a double dupatta: one draped over the head and one over the shoulder.",
      images: [img("maharani-velvet-bridal"), img("maharani-velvet-veil")],
      image_alt: "Bride in a deep maroon velvet lehenga seated on an ornate gold chair",
      sizes: BRIDAL_SIZES,
      colors: ["Maroon", "Antique Gold"],
      fabric: "Velvet with zari embroidery",
      price: 56000,
      availability: "made_to_order",
      is_customizable: true,
      stitching_available: true,
    },
    "wedding-collection",
  ),
  product(
    {
      name: "Saffron Heritage Lehenga Choli",
      slug: "saffron-heritage-lehenga-choli",
      short_description: "Saffron and maroon lehenga choli with gota and mirror detailing, for mehendi and sangeet.",
      description: "A celebratory saffron lehenga with maroon accents, gota patti borders and fine mirror work, styled with a contrast dupatta.",
      images: [img("saffron-heritage-lehenga")],
      image_alt: "Woman in a saffron and maroon embroidered lehenga choli with a red dupatta",
      sizes: ["S", "M", "L", "XL", "Custom"],
      colors: ["Saffron", "Maroon"],
      fabric: "Art silk",
      price: 24500,
      is_customizable: true,
      stitching_available: true,
    },
    "wedding-collection",
  ),
  product(
    {
      name: "Emerald Zardozi Lehenga Choli",
      slug: "emerald-zardozi-lehenga-choli",
      short_description: "Bottle-green lehenga with zardozi work, a striking pick for the bride's sister.",
      images: [img("emerald-lehenga-choli")],
      image_alt: "Woman in an emerald green embroidered lehenga choli",
      sizes: ["S", "M", "L", "XL"],
      colors: ["Emerald Green", "Gold"],
      fabric: "Georgette",
      price: 18900,
      is_customizable: true,
    },
    "wedding-collection",
  ),
  product(
    {
      name: "Ivory Pearl Embellished Lehenga",
      slug: "ivory-pearl-embellished-lehenga",
      short_description: "Ivory lehenga with pearl and sequin embellishment, for engagements and receptions.",
      description: "Understated and luxurious: ivory silk with tonal sequins and hand-placed pearls, paired with a sweetheart-neck blouse.",
      images: [img("ivory-pearl-lehenga")],
      image_alt: "Woman in an ivory pearl-embellished lehenga and blouse",
      sizes: ["S", "M", "L", "XL", "Custom"],
      colors: ["Ivory"],
      fabric: "Silk with pearl embellishment",
      price: 21500,
      is_customizable: true,
      stitching_available: true,
    },
    "wedding-collection",
  ),
  // ── Festive ───────────────────────────────────────────────────────────────
  product(
    {
      name: "Ruby Red Flared Gown",
      slug: "ruby-red-flared-gown",
      short_description: "A floor-length ruby gown with a dramatic flare, for receptions and festive evenings.",
      images: [img("ruby-red-gown")],
      image_alt: "Woman in a flowing ruby red gown with gold jewellery",
      sizes: ["S", "M", "L", "XL"],
      colors: ["Ruby Red"],
      fabric: "Satin silk",
      price: 9800,
    },
    "festive-wear",
  ),
  product(
    {
      name: "Silver Embroidered Crop-Top Lehenga",
      slug: "silver-embroidered-crop-top-lehenga",
      short_description: "Contemporary silver-grey lehenga with a fully embroidered crop top.",
      images: [img("silver-crop-lehenga")],
      image_alt: "Woman in a silver-grey embroidered crop top and lehenga",
      sizes: ["S", "M", "L"],
      colors: ["Silver Grey"],
      fabric: "Net with thread embroidery",
      price: 12500,
    },
    "festive-wear",
  ),
  product(
    {
      name: "Festive Silk Saree with Contrast Blouse",
      slug: "festive-silk-saree-contrast-blouse",
      short_description: "Pistachio silk saree styled with a red brocade blouse, for pujas and family functions.",
      images: [img("festive-silk-saree")],
      image_alt: "Woman in a pistachio silk saree with a red blouse and traditional jewellery",
      colors: ["Pistachio", "Red"],
      fabric: "Silk",
      price: 7450,
      stitching_available: true,
    },
    "womens-ethnic-wear",
  ),
  // ── Blouses ───────────────────────────────────────────────────────────────
  product(
    {
      name: "Antique Zari Velvet Blouse",
      slug: "antique-zari-velvet-blouse",
      is_featured: true,
      featured_order: 5,
      subcategory: "Designer",
      short_description: "Red velvet blouse with antique-gold zari work, made to pair with silk and Kanjeevaram sarees.",
      description:
        "Heirloom-inspired: plush velvet worked with antique zari that has a softly aged, regal finish. The fit is structured, with elbow-length sleeves and a deep back.\n\nThe neckline and sleeve length can be adjusted at your fitting.",
      images: [img("antique-velvet-blouse"), img("zari-detail")],
      image_alt: "Red velvet blouse with antique gold zari embroidery, worn with a red saree",
      sizes: BLOUSE_SIZES,
      colors: ["Red", "Antique Gold"],
      fabric: "Velvet",
      price: 4850,
      is_customizable: true,
      customization_notes: "Neckline, sleeve length and back design can be changed. Padding is available on request.",
      stitching_available: true,
    },
    "antique-blouses",
  ),
  product(
    {
      name: "Red Raw Silk V-Neck Blouse",
      slug: "red-raw-silk-v-neck-blouse",
      short_description: "Deep V-neck raw silk blouse with gold zari borders at the neckline and sleeves.",
      images: [img("red-silk-blouse-front"), img("red-silk-blouse-detail")],
      image_alt: "Red raw silk V-neck blouse with gold borders, worn with an ivory saree",
      sizes: BLOUSE_SIZES,
      colors: ["Red"],
      fabric: "Raw silk",
      price: 3250,
      is_customizable: true,
      stitching_available: true,
    },
    "blouses",
  ),
  product(
    {
      name: "Tie-Back Designer Blouse",
      slug: "tie-back-designer-blouse",
      is_featured: true,
      featured_order: 8,
      subcategory: "Back design",
      short_description: "Open-back blouse with a delicate tie-up, stitched to your measurements.",
      description: "A favourite for weddings and receptions. The open back is finished with a dori tie, and the front can be plain or embellished.",
      images: [img("red-silk-blouse-back"), img("red-silk-blouse-front")],
      image_alt: "Back view of a red designer blouse with an open back and tie-up",
      sizes: BLOUSE_SIZES,
      colors: ["Red", "Made in your colour"],
      fabric: "Silk (or bring your own fabric)",
      price: 2800,
      availability: "made_to_order",
      is_customizable: true,
      customization_notes: "Bring your saree's blouse piece and we'll stitch it in this design.",
      stitching_available: true,
    },
    "custom-blouses",
  ),
  product(
    {
      name: "Puff-Sleeve Silk Blouse",
      slug: "puff-sleeve-silk-blouse",
      short_description: "Magenta silk blouse with statement puff sleeves, made for cotton and silk sarees.",
      images: [img("puff-sleeve-blouse"), img("puff-sleeve-blouse-2")],
      image_alt: "Woman wearing a magenta puff-sleeve blouse with a silk saree",
      sizes: BLOUSE_SIZES,
      colors: ["Magenta"],
      fabric: "Silk",
      price: 2450,
      stitching_available: true,
    },
    "blouses",
  ),
  product(
    {
      name: "Classic Red-Border Saree Blouse",
      slug: "classic-red-border-saree-blouse",
      short_description: "Elbow-sleeve blouse with a gold border, stitched to match your saree.",
      images: [img("bengali-saree-blouse")],
      image_alt: "Woman in a white and red saree with a matching red blouse",
      sizes: BLOUSE_SIZES,
      colors: ["Red", "Gold"],
      fabric: "Cotton silk",
      price: 1950,
      availability: "made_to_order",
      is_customizable: true,
      stitching_available: true,
    },
    "custom-blouses",
  ),
  // ── Chaniya choli ─────────────────────────────────────────────────────────
  product(
    {
      name: "Mustard Navratri Chaniya Choli",
      slug: "mustard-navratri-chaniya-choli",
      subcategory: "Navratri",
      short_description: "Flared mustard chaniya with an ivory choli and a sheer dupatta, made for garba nights.",
      description: "A full, twirl-ready chaniya with a fitted ivory choli and a sheer peach dupatta. It is light and comfortable for long garba nights.",
      images: [img("navratri-chaniya-choli")],
      image_alt: "Woman in a mustard chaniya with an ivory choli and a sheer dupatta",
      sizes: ["S", "M", "L", "XL"],
      colors: ["Mustard", "Ivory", "Peach"],
      fabric: "Georgette",
      price: 6500,
      is_customizable: true,
      stitching_available: true,
    },
    "chaniya-choli",
  ),
  // ── Suits ─────────────────────────────────────────────────────────────────
  product(
    {
      name: "Red Kurta Salwar with Printed Dupatta",
      slug: "red-kurta-salwar-printed-dupatta",
      short_description: "Straight red kurta with yoke embroidery, a salwar and a printed dupatta.",
      images: [img("red-salwar-kurta"), img("red-salwar-kurta-2")],
      image_alt: "Woman in a red embroidered kurta with a printed dupatta",
      sizes: SUIT_SIZES,
      colors: ["Red"],
      fabric: "Cotton blend",
      price: 2850,
      stitching_available: true,
    },
    "salwar-kurta",
  ),
  product(
    {
      name: "Rose Block-Print Kurta Set",
      slug: "rose-block-print-kurta-set",
      short_description: "Soft rose cotton kurta with hand block-printed florals and matching pants.",
      images: [img("rose-kurta-set"), img("pink-salwar-suit")],
      image_alt: "Woman in a rose pink block-printed kurta and pants",
      sizes: SUIT_SIZES,
      colors: ["Rose Pink"],
      fabric: "Cotton",
      price: 3450,
      stitching_available: true,
    },
    "salwar-kurta",
  ),
  product(
    {
      name: "Ivory Embroidered Anarkali Suit",
      slug: "ivory-embroidered-anarkali-suit",
      short_description: "Ivory anarkali with gold embroidery and a sheer dupatta, for festive mornings.",
      images: [img("ivory-anarkali")],
      image_alt: "Woman in an ivory embroidered anarkali with gold work",
      sizes: SUIT_SIZES,
      colors: ["Ivory", "Gold"],
      fabric: "Georgette",
      price: 7250,
      is_customizable: true,
    },
    "salwar-kameez",
  ),
  // ── Girls & kids ──────────────────────────────────────────────────────────
  product(
    {
      name: "Girls' Silk Pavadai Lehenga",
      slug: "girls-silk-pavadai-lehenga",
      short_description: "Traditional silk pavadai with a zari border and a contrast blouse.",
      images: [img("girls-silk-lehenga"), img("girls-silk-lehenga-2")],
      image_alt: "Little girl in a cream silk pavadai with a navy blouse, holding a flower basket",
      sizes: ["2–3 yrs", "4–5 yrs", "6–7 yrs", "8–9 yrs", "10–12 yrs"],
      colors: ["Cream", "Navy"],
      fabric: "Silk",
      price: 3200,
      stitching_available: true,
    },
    "girls-wear",
  ),
  product(
    {
      name: "Girls' Red Silk Lehenga Choli",
      slug: "girls-red-silk-lehenga-choli",
      short_description: "Bright red lehenga choli for festivals, weddings and dance functions.",
      images: [img("girls-red-lehenga")],
      image_alt: "Young girl in a red silk lehenga choli",
      sizes: ["4–5 yrs", "6–7 yrs", "8–9 yrs", "10–12 yrs"],
      colors: ["Red", "Gold"],
      fabric: "Art silk",
      price: 2950,
    },
    "girls-wear",
  ),
  product(
    {
      name: "Little Princess Festive Set",
      slug: "little-princess-festive-set",
      short_description: "Red brocade festive outfit for little ones. Jewellery is not included.",
      images: [img("girls-festive-set")],
      image_alt: "Little girl in a red brocade festive outfit with traditional jewellery",
      sizes: ["2–3 yrs", "4–5 yrs", "6–7 yrs"],
      colors: ["Red"],
      fabric: "Brocade",
      price: 3650,
    },
    "kids-traditional-wear",
  ),
  product(
    {
      name: "Baby's First Festival Kurta Set",
      slug: "babys-first-festival-kurta-set",
      short_description: "Soft cotton-silk kurta set in festive saffron, gentle on baby's skin.",
      images: [img("kids-festive-kurta")],
      image_alt: "Smiling toddler in a saffron festive kurta",
      sizes: ["6–12 m", "1–2 yrs", "2–3 yrs"],
      colors: ["Saffron"],
      fabric: "Cotton silk",
      price: 1450,
    },
    "kids-traditional-wear",
  ),
  // ── Made for you ──────────────────────────────────────────────────────────
  product(
    {
      name: "Bespoke Bridal Couture",
      slug: "bespoke-bridal-couture",
      short_description: "Your bridal outfit designed from scratch, from the first sketch to the final fitting.",
      description:
        "Share your inspiration with us: a photo, your mother's saree, or just a colour you love. We'll design the outfit with you, source the fabric and stitch it to your measurements with fittings along the way.\n\nPrices depend on the fabric and the embroidery. Message us on WhatsApp to begin.",
      images: [img("bridal-portrait-4"), img("zari-detail")],
      image_alt: "Bride in a custom-designed embroidered outfit with traditional jewellery",
      sizes: BRIDAL_SIZES,
      price: null,
      availability: "made_to_order",
      is_customizable: true,
      stitching_available: true,
    },
    "custom-designs",
  ),
  product(
    {
      name: "Bridal Blouse Stitching",
      slug: "bridal-blouse-stitching",
      short_description: "Bring your blouse piece. We'll design and stitch it with lining, cups and finishing.",
      images: [img("zari-detail-3")],
      image_alt: "Close-up of red and gold zari embroidery on a bridal blouse",
      sizes: ["Made to measure"],
      price: null,
      availability: "made_to_order",
      is_customizable: true,
      stitching_available: true,
    },
    "stitching-services",
  ),
  // ── Additional catalogue ──────────────────────────────────────────────────
  product(
    {
      name: "Shehzadi Red Bridal Lehenga",
      slug: "shehzadi-red-bridal-lehenga",
      is_featured: true,
      featured_order: 1,
      subcategory: "Bridal lehenga",
      short_description: "Velvet-touch red bridal lehenga with gold resham and zari jaal, a timeless royal bridal look.",
      description:
        "Inspired by royal trousseau pieces, this lehenga pairs a fully embroidered blouse with a richly worked skirt and a scalloped net dupatta.\n\nThe blouse is made to measure, with the sleeve length and neckline chosen at your fitting. Please allow 4 to 6 weeks.",
      images: [img("shehzadi-bridal-2"), img("shehzadi-bridal-1"), img("shehzadi-bridal-3")],
      image_alt: "Bride in a red lehenga with gold embroidery and emerald kundan jewellery",
      sizes: BRIDAL_SIZES,
      colors: ["Bridal Red", "Gold"],
      fabric: "Velvet and raw silk",
      price: 62000,
      availability: "made_to_order",
      is_customizable: true,
      stitching_available: true,
    },
    "bridal-wear",
  ),
  product(
    {
      name: "Mint Green Wedding Lehenga",
      slug: "mint-green-wedding-lehenga",
      short_description: "Mint lehenga with tonal thread work and a sheer gold-edged dupatta, made for day weddings.",
      images: [img("mint-wedding-lehenga")],
      image_alt: "Woman in a mint green embroidered lehenga with a sheer dupatta",
      sizes: ["S", "M", "L", "XL", "Custom"],
      colors: ["Mint Green", "Gold"],
      fabric: "Georgette with thread work",
      price: 16500,
      is_customizable: true,
      stitching_available: true,
    },
    "wedding-collection",
  ),
  product(
    {
      name: "Leheriya Chaniya Choli",
      slug: "leheriya-chaniya-choli",
      is_featured: true,
      featured_order: 3,
      subcategory: "Navratri",
      short_description: "Red and pink leheriya chaniya with a gota border, made to swirl through every garba round.",
      images: [img("leheriya-chaniya-choli")],
      image_alt: "Woman in a red and pink striped leheriya chaniya choli",
      sizes: ["S", "M", "L", "XL", "Custom"],
      colors: ["Red", "Rani Pink"],
      fabric: "Cotton silk",
      price: 5850,
      is_customizable: true,
      stitching_available: true,
    },
    "chaniya-choli",
  ),
  product(
    {
      name: "Maroon Embroidered Lehenga Choli",
      slug: "maroon-embroidered-lehenga-choli",
      short_description: "Wine-maroon lehenga choli with a fully embroidered crop blouse.",
      images: [img("maroon-lehenga-choli")],
      image_alt: "Woman in a maroon lehenga choli with an embroidered crop blouse",
      sizes: ["S", "M", "L", "XL"],
      colors: ["Maroon"],
      fabric: "Silk blend",
      price: 14200,
      is_customizable: true,
    },
    "festive-wear",
  ),
  product(
    {
      name: "Black & Gold Lehenga Choli",
      slug: "black-gold-lehenga-choli",
      short_description: "Dramatic black lehenga with antique-gold embroidery, for sangeet and cocktail nights.",
      images: [img("black-gold-lehenga")],
      image_alt: "Woman in a black and gold embroidered lehenga choli",
      sizes: ["S", "M", "L"],
      colors: ["Black", "Antique Gold"],
      fabric: "Velvet",
      price: 13800,
    },
    "festive-wear",
  ),
  product(
    {
      name: "Midnight Navy Pre-Draped Saree",
      slug: "midnight-navy-pre-draped-saree",
      short_description: "Ready-to-wear navy saree with a sequinned blouse. It's on in minutes, elegant all night.",
      images: [img("navy-predraped-saree")],
      image_alt: "Woman in a midnight navy pre-draped saree with a sequinned blouse",
      sizes: ["S", "M", "L", "XL"],
      colors: ["Navy"],
      fabric: "Satin georgette",
      price: 8900,
    },
    "festive-wear",
  ),
  product(
    {
      name: "Emerald Ruffle Saree with Designer Blouse",
      slug: "emerald-ruffle-saree-designer-blouse",
      short_description: "Emerald ruffle saree with a gold border and an embellished designer blouse.",
      images: [img("emerald-ruffle-saree"), img("emerald-ruffle-saree-back")],
      image_alt: "Woman in an emerald green ruffle saree with a gold border",
      colors: ["Emerald", "Gold"],
      fabric: "Georgette",
      price: 9450,
      stitching_available: true,
    },
    "womens-ethnic-wear",
  ),
  product(
    {
      name: "Turquoise Zari-Sleeve Blouse",
      slug: "turquoise-zari-sleeve-blouse",
      is_featured: true,
      featured_order: 2,
      subcategory: "Designer",
      short_description: "Turquoise silk blouse with heavy gold zari on the sleeves, made to pair with Kanjeevaram sarees.",
      images: [img("turquoise-zari-blouse")],
      image_alt: "Close-up of a turquoise silk blouse sleeve with gold zari embroidery",
      sizes: BLOUSE_SIZES,
      colors: ["Turquoise", "Gold"],
      fabric: "Pure silk",
      price: 3950,
      is_customizable: true,
      stitching_available: true,
    },
    "blouses",
  ),
  product(
    {
      name: "Navy Velvet Zardozi Blouse",
      slug: "navy-velvet-zardozi-blouse",
      subcategory: "Antique",
      short_description: "Navy velvet blouse with antique zardozi motifs on the sleeves.",
      images: [img("navy-velvet-zardozi-blouse")],
      image_alt: "Close-up of a navy velvet blouse with antique gold zardozi on the sleeve",
      sizes: BLOUSE_SIZES,
      colors: ["Navy", "Antique Gold"],
      fabric: "Velvet",
      price: 5250,
      is_customizable: true,
      stitching_available: true,
    },
    "antique-blouses",
  ),
  product(
    {
      name: "Red Silk Blouse with Kasavu Saree",
      slug: "red-silk-blouse-kasavu-saree",
      short_description: "Long-sleeve red silk blouse styled with a gold tissue saree.",
      images: [img("red-blouse-drape")],
      image_alt: "Woman in a red long-sleeve silk blouse and gold tissue saree",
      sizes: BLOUSE_SIZES,
      colors: ["Red", "Gold"],
      fabric: "Silk",
      price: 2750,
      stitching_available: true,
    },
    "blouses",
  ),
  product(
    {
      name: "Royal Blue Embroidered Salwar Suit",
      slug: "royal-blue-embroidered-salwar-suit",
      is_featured: true,
      featured_order: 6,
      short_description: "Royal blue straight suit with dense yoke embroidery and a contrast dupatta.",
      images: [img("blue-salwar-suit")],
      image_alt: "Woman in a royal blue embroidered salwar suit with a beige dupatta",
      sizes: SUIT_SIZES,
      colors: ["Royal Blue"],
      fabric: "Chanderi silk",
      price: 4650,
      stitching_available: true,
    },
    "salwar-kameez",
  ),
  product(
    {
      name: "Ivory Block-Print Kurta Set",
      slug: "ivory-block-print-kurta-set",
      short_description: "Breathable ivory cotton kurta with hand block-printed florals and matching pants.",
      images: [img("ivory-kurta-set")],
      image_alt: "Woman in an ivory floral block-printed kurta and pants",
      sizes: SUIT_SIZES,
      colors: ["Ivory", "Rose"],
      fabric: "Cotton",
      price: 2450,
      stitching_available: true,
    },
    "salwar-kurta",
  ),
  product(
    {
      name: "Girls' Dandiya Chaniya Choli",
      slug: "girls-dandiya-chaniya-choli",
      is_featured: true,
      featured_order: 7,
      short_description: "Bright red chaniya choli for little garba stars, light and easy to dance in.",
      images: [img("girls-dandiya-chaniya")],
      image_alt: "Smiling girl in a red chaniya choli holding dandiya sticks",
      sizes: ["4–5 yrs", "6–7 yrs", "8–9 yrs", "10–12 yrs"],
      colors: ["Red", "Blue"],
      fabric: "Cotton silk",
      price: 2250,
    },
    "girls-wear",
  ),
  product(
    {
      name: "Pearl-Beaded Cape Saree",
      slug: "pearl-beaded-cape-saree",
      subcategory: "Couture",
      short_description: "A custom couture piece: a champagne saree with a hand-beaded cape blouse.",
      images: [img("pearl-cape-saree")],
      image_alt: "Woman in a champagne saree with a hand-beaded cape",
      sizes: BRIDAL_SIZES,
      colors: ["Champagne"],
      fabric: "Satin with hand beading",
      price: 18500,
      availability: "made_to_order",
      is_customizable: true,
      stitching_available: true,
    },
    "custom-designs",
  ),
];

/** In preview mode, "today" is shown at the boutique with the default hours. */
export function demoTodayLocation(): DailyLocation {
  return {
    id: "demo-today",
    date: todayInStore(),
    location_name: "Geeta Fashion Hub Boutique",
    address: "Our permanent boutique",
    maps_url: defaultSettings.maps_url,
    open_time: "10:30",
    close_time: "20:30",
    is_open: true,
    announcement: "The festive and wedding season collection is now in store. Bridal fittings are by appointment on WhatsApp.",
  };
}

/** Lookbook tiles for the Instagram section in preview mode. They link to the real profile. */
export const demoLookbook: InstagramPost[] = [
  "shehzadi-bridal-3",
  "bridal-portrait-2",
  "juttis",
  "emerald-ruffle-saree-back",
  "festive-portrait",
  "bridal-mirror",
  "pink-bridal-lehenga-full",
  "zari-detail-2",
].map((name) => ({
  id: `look-${name}`,
  permalink: defaultSettings.instagram_url,
  image_url: img(name),
  caption: null,
  is_video: false,
}));
