-- Starter catalogue (optional). Run after seed.sql to start with a full, realistic catalogue.
-- Photos are bundled Unsplash stand-ins under /images/lookbook. Replace them with your own photos in /admin.
-- Prices are realistic starting points. Review every product before going live.

update public.categories set image_url = '/images/lookbook/turquoise-zari-blouse.jpg' where slug = 'blouses' and image_url is null;
update public.categories set image_url = '/images/lookbook/navy-velvet-zardozi-blouse.jpg' where slug = 'antique-blouses' and image_url is null;
update public.categories set image_url = '/images/lookbook/red-silk-blouse-back.jpg' where slug = 'custom-blouses' and image_url is null;
update public.categories set image_url = '/images/lookbook/leheriya-chaniya-choli.jpg' where slug = 'chaniya-choli' and image_url is null;
update public.categories set image_url = '/images/lookbook/blue-salwar-suit.jpg' where slug = 'salwar-kameez' and image_url is null;
update public.categories set image_url = '/images/lookbook/ivory-kurta-set.jpg' where slug = 'salwar-kurta' and image_url is null;
update public.categories set image_url = '/images/lookbook/shehzadi-bridal-2.jpg' where slug = 'bridal-wear' and image_url is null;
update public.categories set image_url = '/images/lookbook/mint-wedding-lehenga.jpg' where slug = 'wedding-collection' and image_url is null;
update public.categories set image_url = '/images/lookbook/maroon-lehenga-choli.jpg' where slug = 'festive-wear' and image_url is null;
update public.categories set image_url = '/images/lookbook/emerald-ruffle-saree.jpg' where slug = 'womens-ethnic-wear' and image_url is null;
update public.categories set image_url = '/images/lookbook/girls-dandiya-chaniya.jpg' where slug = 'girls-wear' and image_url is null;
update public.categories set image_url = '/images/lookbook/girls-silk-lehenga.jpg' where slug = 'kids-traditional-wear' and image_url is null;
update public.categories set image_url = '/images/lookbook/pearl-cape-saree.jpg' where slug = 'custom-designs' and image_url is null;
update public.categories set image_url = '/images/lookbook/red-silk-blouse-back.jpg' where slug = 'stitching-services' and image_url is null;

update public.site_settings set hero_image_url = coalesce(hero_image_url, '/images/lookbook/hero-brides.jpg'), business_hours = case when business_hours = '[]'::jsonb then '[{"day":"Monday","open":"10:30","close":"20:30","closed":false},{"day":"Tuesday","open":"10:30","close":"20:30","closed":false},{"day":"Wednesday","open":"10:30","close":"20:30","closed":false},{"day":"Thursday","open":"10:30","close":"20:30","closed":false},{"day":"Friday","open":"10:30","close":"20:30","closed":false},{"day":"Saturday","open":"10:30","close":"20:30","closed":false},{"day":"Sunday","open":"10:30","close":"20:30","closed":false}]'::jsonb else business_hours end, hours_note = coalesce(hours_note, 'Timings may change on festival days. Check today''s location before you visit.') where id = 1;

insert into public.products (name, slug, category_id, subcategory, short_description, description, images, image_alt, sizes, colors, fabric, price, is_customizable, customization_notes, stitching_available, availability, is_featured, featured_order, is_visible) values ('Maharani Red Bridal Lehenga', 'maharani-red-bridal-lehenga', (select id from public.categories where slug = 'bridal-wear'), 'Bridal lehenga', 'A classic bridal red lehenga with dense zari and sequin work, paired with a matching blouse and net dupatta.', 'Our signature bridal lehenga, made for the bride who loves tradition. The flared skirt carries heavy zari, dabka and sequin work across every panel, finished with a scalloped border that catches the light as you walk.

The blouse is stitched to your measurements, and the neckline, sleeve length and back design can all be chosen during your fitting. A soft net dupatta with an embroidered border completes the look.

Please allow 3 to 5 weeks for stitching and two fittings.', array['/images/lookbook/red-bridal-lehenga.jpg', '/images/lookbook/zari-detail-2.jpg', '/images/lookbook/zari-detail-3.jpg']::text[], 'Bride in a red lehenga with heavy gold zari embroidery and a red net dupatta', array['Made to measure']::text[], array['Bridal Red', 'Antique Gold']::text[], 'Raw silk with net dupatta', 48500, true, 'Choose the blouse neckline, sleeve style and back design. The embroidery colour can be matched to your jewellery.', true, 'made_to_order', false, 0, true) on conflict (slug) do nothing;
insert into public.products (name, slug, category_id, subcategory, short_description, description, images, image_alt, sizes, colors, fabric, price, is_customizable, customization_notes, stitching_available, availability, is_featured, featured_order, is_visible) values ('Rani Pink Bridal Lehenga', 'rani-pink-bridal-lehenga', (select id from public.categories where slug = 'bridal-wear'), 'Bridal lehenga', 'Rani pink lehenga with gold zardozi, made for day weddings and receptions.', 'A joyful rani pink lehenga with gold zardozi motifs and a heavy border. It is light enough for day functions yet grand enough for the wedding itself.

Stitched to measure, with your choice of blouse design.', array['/images/lookbook/pink-bridal-lehenga-full.jpg', '/images/lookbook/rani-pink-bridal.jpg', '/images/lookbook/bridal-portrait-2.jpg']::text[], 'Bride in a rani pink lehenga with gold zardozi embroidery and kundan jewellery', array['Made to measure']::text[], array['Rani Pink', 'Gold']::text[], 'Silk blend', 42000, true, null, true, 'made_to_order', false, 0, true) on conflict (slug) do nothing;
insert into public.products (name, slug, category_id, subcategory, short_description, description, images, image_alt, sizes, colors, fabric, price, is_customizable, customization_notes, stitching_available, availability, is_featured, featured_order, is_visible) values ('Royal Maroon Velvet Lehenga', 'royal-maroon-velvet-lehenga', (select id from public.categories where slug = 'wedding-collection'), 'Wedding lehenga', 'Deep maroon velvet with all-over antique zari, a regal choice for the wedding night.', 'Rich maroon velvet embroidered with antique-gold zari in traditional jaal patterns. It has a structured, heavy fall and photographs beautifully under evening light.

It pairs with a double dupatta: one draped over the head and one over the shoulder.', array['/images/lookbook/maharani-velvet-bridal.jpg', '/images/lookbook/maharani-velvet-veil.jpg']::text[], 'Bride in a deep maroon velvet lehenga seated on an ornate gold chair', array['Made to measure']::text[], array['Maroon', 'Antique Gold']::text[], 'Velvet with zari embroidery', 56000, true, null, true, 'made_to_order', true, 4, true) on conflict (slug) do nothing;
insert into public.products (name, slug, category_id, subcategory, short_description, description, images, image_alt, sizes, colors, fabric, price, is_customizable, customization_notes, stitching_available, availability, is_featured, featured_order, is_visible) values ('Saffron Heritage Lehenga Choli', 'saffron-heritage-lehenga-choli', (select id from public.categories where slug = 'wedding-collection'), null, 'Saffron and maroon lehenga choli with gota and mirror detailing, for mehendi and sangeet.', 'A celebratory saffron lehenga with maroon accents, gota patti borders and fine mirror work, styled with a contrast dupatta.', array['/images/lookbook/saffron-heritage-lehenga.jpg']::text[], 'Woman in a saffron and maroon embroidered lehenga choli with a red dupatta', array['S', 'M', 'L', 'XL', 'Custom']::text[], array['Saffron', 'Maroon']::text[], 'Art silk', 24500, true, null, true, 'in_stock', false, 0, true) on conflict (slug) do nothing;
insert into public.products (name, slug, category_id, subcategory, short_description, description, images, image_alt, sizes, colors, fabric, price, is_customizable, customization_notes, stitching_available, availability, is_featured, featured_order, is_visible) values ('Emerald Zardozi Lehenga Choli', 'emerald-zardozi-lehenga-choli', (select id from public.categories where slug = 'wedding-collection'), null, 'Bottle-green lehenga with zardozi work, a striking pick for the bride''s sister.', null, array['/images/lookbook/emerald-lehenga-choli.jpg']::text[], 'Woman in an emerald green embroidered lehenga choli', array['S', 'M', 'L', 'XL']::text[], array['Emerald Green', 'Gold']::text[], 'Georgette', 18900, true, null, false, 'in_stock', false, 0, true) on conflict (slug) do nothing;
insert into public.products (name, slug, category_id, subcategory, short_description, description, images, image_alt, sizes, colors, fabric, price, is_customizable, customization_notes, stitching_available, availability, is_featured, featured_order, is_visible) values ('Ivory Pearl Embellished Lehenga', 'ivory-pearl-embellished-lehenga', (select id from public.categories where slug = 'wedding-collection'), null, 'Ivory lehenga with pearl and sequin embellishment, for engagements and receptions.', 'Understated and luxurious: ivory silk with tonal sequins and hand-placed pearls, paired with a sweetheart-neck blouse.', array['/images/lookbook/ivory-pearl-lehenga.jpg']::text[], 'Woman in an ivory pearl-embellished lehenga and blouse', array['S', 'M', 'L', 'XL', 'Custom']::text[], array['Ivory']::text[], 'Silk with pearl embellishment', 21500, true, null, true, 'in_stock', false, 0, true) on conflict (slug) do nothing;
insert into public.products (name, slug, category_id, subcategory, short_description, description, images, image_alt, sizes, colors, fabric, price, is_customizable, customization_notes, stitching_available, availability, is_featured, featured_order, is_visible) values ('Ruby Red Flared Gown', 'ruby-red-flared-gown', (select id from public.categories where slug = 'festive-wear'), null, 'A floor-length ruby gown with a dramatic flare, for receptions and festive evenings.', null, array['/images/lookbook/ruby-red-gown.jpg']::text[], 'Woman in a flowing ruby red gown with gold jewellery', array['S', 'M', 'L', 'XL']::text[], array['Ruby Red']::text[], 'Satin silk', 9800, false, null, false, 'in_stock', false, 0, true) on conflict (slug) do nothing;
insert into public.products (name, slug, category_id, subcategory, short_description, description, images, image_alt, sizes, colors, fabric, price, is_customizable, customization_notes, stitching_available, availability, is_featured, featured_order, is_visible) values ('Silver Embroidered Crop-Top Lehenga', 'silver-embroidered-crop-top-lehenga', (select id from public.categories where slug = 'festive-wear'), null, 'Contemporary silver-grey lehenga with a fully embroidered crop top.', null, array['/images/lookbook/silver-crop-lehenga.jpg']::text[], 'Woman in a silver-grey embroidered crop top and lehenga', array['S', 'M', 'L']::text[], array['Silver Grey']::text[], 'Net with thread embroidery', 12500, false, null, false, 'in_stock', false, 0, true) on conflict (slug) do nothing;
insert into public.products (name, slug, category_id, subcategory, short_description, description, images, image_alt, sizes, colors, fabric, price, is_customizable, customization_notes, stitching_available, availability, is_featured, featured_order, is_visible) values ('Festive Silk Saree with Contrast Blouse', 'festive-silk-saree-contrast-blouse', (select id from public.categories where slug = 'womens-ethnic-wear'), null, 'Pistachio silk saree styled with a red brocade blouse, for pujas and family functions.', null, array['/images/lookbook/festive-silk-saree.jpg']::text[], 'Woman in a pistachio silk saree with a red blouse and traditional jewellery', '{}'::text[], array['Pistachio', 'Red']::text[], 'Silk', 7450, false, null, true, 'in_stock', false, 0, true) on conflict (slug) do nothing;
insert into public.products (name, slug, category_id, subcategory, short_description, description, images, image_alt, sizes, colors, fabric, price, is_customizable, customization_notes, stitching_available, availability, is_featured, featured_order, is_visible) values ('Antique Zari Velvet Blouse', 'antique-zari-velvet-blouse', (select id from public.categories where slug = 'antique-blouses'), 'Designer', 'Red velvet blouse with antique-gold zari work, made to pair with silk and Kanjeevaram sarees.', 'Heirloom-inspired: plush velvet worked with antique zari that has a softly aged, regal finish. The fit is structured, with elbow-length sleeves and a deep back.

The neckline and sleeve length can be adjusted at your fitting.', array['/images/lookbook/antique-velvet-blouse.jpg', '/images/lookbook/zari-detail.jpg']::text[], 'Red velvet blouse with antique gold zari embroidery, worn with a red saree', array['32', '34', '36', '38', '40', '42', 'Custom']::text[], array['Red', 'Antique Gold']::text[], 'Velvet', 4850, true, 'Neckline, sleeve length and back design can be changed. Padding is available on request.', true, 'in_stock', true, 5, true) on conflict (slug) do nothing;
insert into public.products (name, slug, category_id, subcategory, short_description, description, images, image_alt, sizes, colors, fabric, price, is_customizable, customization_notes, stitching_available, availability, is_featured, featured_order, is_visible) values ('Red Raw Silk V-Neck Blouse', 'red-raw-silk-v-neck-blouse', (select id from public.categories where slug = 'blouses'), null, 'Deep V-neck raw silk blouse with gold zari borders at the neckline and sleeves.', null, array['/images/lookbook/red-silk-blouse-front.jpg', '/images/lookbook/red-silk-blouse-detail.jpg']::text[], 'Red raw silk V-neck blouse with gold borders, worn with an ivory saree', array['32', '34', '36', '38', '40', '42', 'Custom']::text[], array['Red']::text[], 'Raw silk', 3250, true, null, true, 'in_stock', false, 0, true) on conflict (slug) do nothing;
insert into public.products (name, slug, category_id, subcategory, short_description, description, images, image_alt, sizes, colors, fabric, price, is_customizable, customization_notes, stitching_available, availability, is_featured, featured_order, is_visible) values ('Tie-Back Designer Blouse', 'tie-back-designer-blouse', (select id from public.categories where slug = 'custom-blouses'), 'Back design', 'Open-back blouse with a delicate tie-up, stitched to your measurements.', 'A favourite for weddings and receptions. The open back is finished with a dori tie, and the front can be plain or embellished.', array['/images/lookbook/red-silk-blouse-back.jpg', '/images/lookbook/red-silk-blouse-front.jpg']::text[], 'Back view of a red designer blouse with an open back and tie-up', array['32', '34', '36', '38', '40', '42', 'Custom']::text[], array['Red', 'Made in your colour']::text[], 'Silk (or bring your own fabric)', 2800, true, 'Bring your saree''s blouse piece and we''ll stitch it in this design.', true, 'made_to_order', true, 8, true) on conflict (slug) do nothing;
insert into public.products (name, slug, category_id, subcategory, short_description, description, images, image_alt, sizes, colors, fabric, price, is_customizable, customization_notes, stitching_available, availability, is_featured, featured_order, is_visible) values ('Puff-Sleeve Silk Blouse', 'puff-sleeve-silk-blouse', (select id from public.categories where slug = 'blouses'), null, 'Magenta silk blouse with statement puff sleeves, made for cotton and silk sarees.', null, array['/images/lookbook/puff-sleeve-blouse.jpg', '/images/lookbook/puff-sleeve-blouse-2.jpg']::text[], 'Woman wearing a magenta puff-sleeve blouse with a silk saree', array['32', '34', '36', '38', '40', '42', 'Custom']::text[], array['Magenta']::text[], 'Silk', 2450, false, null, true, 'in_stock', false, 0, true) on conflict (slug) do nothing;
insert into public.products (name, slug, category_id, subcategory, short_description, description, images, image_alt, sizes, colors, fabric, price, is_customizable, customization_notes, stitching_available, availability, is_featured, featured_order, is_visible) values ('Classic Red-Border Saree Blouse', 'classic-red-border-saree-blouse', (select id from public.categories where slug = 'custom-blouses'), null, 'Elbow-sleeve blouse with a gold border, stitched to match your saree.', null, array['/images/lookbook/bengali-saree-blouse.jpg']::text[], 'Woman in a white and red saree with a matching red blouse', array['32', '34', '36', '38', '40', '42', 'Custom']::text[], array['Red', 'Gold']::text[], 'Cotton silk', 1950, true, null, true, 'made_to_order', false, 0, true) on conflict (slug) do nothing;
insert into public.products (name, slug, category_id, subcategory, short_description, description, images, image_alt, sizes, colors, fabric, price, is_customizable, customization_notes, stitching_available, availability, is_featured, featured_order, is_visible) values ('Mustard Navratri Chaniya Choli', 'mustard-navratri-chaniya-choli', (select id from public.categories where slug = 'chaniya-choli'), 'Navratri', 'Flared mustard chaniya with an ivory choli and a sheer dupatta, made for garba nights.', 'A full, twirl-ready chaniya with a fitted ivory choli and a sheer peach dupatta. It is light and comfortable for long garba nights.', array['/images/lookbook/navratri-chaniya-choli.jpg']::text[], 'Woman in a mustard chaniya with an ivory choli and a sheer dupatta', array['S', 'M', 'L', 'XL']::text[], array['Mustard', 'Ivory', 'Peach']::text[], 'Georgette', 6500, true, null, true, 'in_stock', false, 0, true) on conflict (slug) do nothing;
insert into public.products (name, slug, category_id, subcategory, short_description, description, images, image_alt, sizes, colors, fabric, price, is_customizable, customization_notes, stitching_available, availability, is_featured, featured_order, is_visible) values ('Red Kurta Salwar with Printed Dupatta', 'red-kurta-salwar-printed-dupatta', (select id from public.categories where slug = 'salwar-kurta'), null, 'Straight red kurta with yoke embroidery, a salwar and a printed dupatta.', null, array['/images/lookbook/red-salwar-kurta.jpg', '/images/lookbook/red-salwar-kurta-2.jpg']::text[], 'Woman in a red embroidered kurta with a printed dupatta', array['S', 'M', 'L', 'XL', 'XXL', 'Custom']::text[], array['Red']::text[], 'Cotton blend', 2850, false, null, true, 'in_stock', false, 0, true) on conflict (slug) do nothing;
insert into public.products (name, slug, category_id, subcategory, short_description, description, images, image_alt, sizes, colors, fabric, price, is_customizable, customization_notes, stitching_available, availability, is_featured, featured_order, is_visible) values ('Rose Block-Print Kurta Set', 'rose-block-print-kurta-set', (select id from public.categories where slug = 'salwar-kurta'), null, 'Soft rose cotton kurta with hand block-printed florals and matching pants.', null, array['/images/lookbook/rose-kurta-set.jpg', '/images/lookbook/pink-salwar-suit.jpg']::text[], 'Woman in a rose pink block-printed kurta and pants', array['S', 'M', 'L', 'XL', 'XXL', 'Custom']::text[], array['Rose Pink']::text[], 'Cotton', 3450, false, null, true, 'in_stock', false, 0, true) on conflict (slug) do nothing;
insert into public.products (name, slug, category_id, subcategory, short_description, description, images, image_alt, sizes, colors, fabric, price, is_customizable, customization_notes, stitching_available, availability, is_featured, featured_order, is_visible) values ('Ivory Embroidered Anarkali Suit', 'ivory-embroidered-anarkali-suit', (select id from public.categories where slug = 'salwar-kameez'), null, 'Ivory anarkali with gold embroidery and a sheer dupatta, for festive mornings.', null, array['/images/lookbook/ivory-anarkali.jpg']::text[], 'Woman in an ivory embroidered anarkali with gold work', array['S', 'M', 'L', 'XL', 'XXL', 'Custom']::text[], array['Ivory', 'Gold']::text[], 'Georgette', 7250, true, null, false, 'in_stock', false, 0, true) on conflict (slug) do nothing;
insert into public.products (name, slug, category_id, subcategory, short_description, description, images, image_alt, sizes, colors, fabric, price, is_customizable, customization_notes, stitching_available, availability, is_featured, featured_order, is_visible) values ('Girls'' Silk Pavadai Lehenga', 'girls-silk-pavadai-lehenga', (select id from public.categories where slug = 'girls-wear'), null, 'Traditional silk pavadai with a zari border and a contrast blouse.', null, array['/images/lookbook/girls-silk-lehenga.jpg', '/images/lookbook/girls-silk-lehenga-2.jpg']::text[], 'Little girl in a cream silk pavadai with a navy blouse, holding a flower basket', array['2–3 yrs', '4–5 yrs', '6–7 yrs', '8–9 yrs', '10–12 yrs']::text[], array['Cream', 'Navy']::text[], 'Silk', 3200, false, null, true, 'in_stock', false, 0, true) on conflict (slug) do nothing;
insert into public.products (name, slug, category_id, subcategory, short_description, description, images, image_alt, sizes, colors, fabric, price, is_customizable, customization_notes, stitching_available, availability, is_featured, featured_order, is_visible) values ('Girls'' Red Silk Lehenga Choli', 'girls-red-silk-lehenga-choli', (select id from public.categories where slug = 'girls-wear'), null, 'Bright red lehenga choli for festivals, weddings and dance functions.', null, array['/images/lookbook/girls-red-lehenga.jpg']::text[], 'Young girl in a red silk lehenga choli', array['4–5 yrs', '6–7 yrs', '8–9 yrs', '10–12 yrs']::text[], array['Red', 'Gold']::text[], 'Art silk', 2950, false, null, false, 'in_stock', false, 0, true) on conflict (slug) do nothing;
insert into public.products (name, slug, category_id, subcategory, short_description, description, images, image_alt, sizes, colors, fabric, price, is_customizable, customization_notes, stitching_available, availability, is_featured, featured_order, is_visible) values ('Little Princess Festive Set', 'little-princess-festive-set', (select id from public.categories where slug = 'kids-traditional-wear'), null, 'Red brocade festive outfit for little ones. Jewellery is not included.', null, array['/images/lookbook/girls-festive-set.jpg']::text[], 'Little girl in a red brocade festive outfit with traditional jewellery', array['2–3 yrs', '4–5 yrs', '6–7 yrs']::text[], array['Red']::text[], 'Brocade', 3650, false, null, false, 'in_stock', false, 0, true) on conflict (slug) do nothing;
insert into public.products (name, slug, category_id, subcategory, short_description, description, images, image_alt, sizes, colors, fabric, price, is_customizable, customization_notes, stitching_available, availability, is_featured, featured_order, is_visible) values ('Baby''s First Festival Kurta Set', 'babys-first-festival-kurta-set', (select id from public.categories where slug = 'kids-traditional-wear'), null, 'Soft cotton-silk kurta set in festive saffron, gentle on baby''s skin.', null, array['/images/lookbook/kids-festive-kurta.jpg']::text[], 'Smiling toddler in a saffron festive kurta', array['6–12 m', '1–2 yrs', '2–3 yrs']::text[], array['Saffron']::text[], 'Cotton silk', 1450, false, null, false, 'in_stock', false, 0, true) on conflict (slug) do nothing;
insert into public.products (name, slug, category_id, subcategory, short_description, description, images, image_alt, sizes, colors, fabric, price, is_customizable, customization_notes, stitching_available, availability, is_featured, featured_order, is_visible) values ('Bespoke Bridal Couture', 'bespoke-bridal-couture', (select id from public.categories where slug = 'custom-designs'), null, 'Your bridal outfit designed from scratch, from the first sketch to the final fitting.', 'Share your inspiration with us: a photo, your mother''s saree, or just a colour you love. We''ll design the outfit with you, source the fabric and stitch it to your measurements with fittings along the way.

Prices depend on the fabric and the embroidery. Message us on WhatsApp to begin.', array['/images/lookbook/bridal-portrait-4.jpg', '/images/lookbook/zari-detail.jpg']::text[], 'Bride in a custom-designed embroidered outfit with traditional jewellery', array['Made to measure']::text[], '{}'::text[], null, null, true, null, true, 'made_to_order', false, 0, true) on conflict (slug) do nothing;
insert into public.products (name, slug, category_id, subcategory, short_description, description, images, image_alt, sizes, colors, fabric, price, is_customizable, customization_notes, stitching_available, availability, is_featured, featured_order, is_visible) values ('Bridal Blouse Stitching', 'bridal-blouse-stitching', (select id from public.categories where slug = 'stitching-services'), null, 'Bring your blouse piece. We''ll design and stitch it with lining, cups and finishing.', null, array['/images/lookbook/zari-detail-3.jpg']::text[], 'Close-up of red and gold zari embroidery on a bridal blouse', array['Made to measure']::text[], '{}'::text[], null, null, true, null, true, 'made_to_order', false, 0, true) on conflict (slug) do nothing;
insert into public.products (name, slug, category_id, subcategory, short_description, description, images, image_alt, sizes, colors, fabric, price, is_customizable, customization_notes, stitching_available, availability, is_featured, featured_order, is_visible) values ('Shehzadi Red Bridal Lehenga', 'shehzadi-red-bridal-lehenga', (select id from public.categories where slug = 'bridal-wear'), 'Bridal lehenga', 'Velvet-touch red bridal lehenga with gold resham and zari jaal, a timeless royal bridal look.', 'Inspired by royal trousseau pieces, this lehenga pairs a fully embroidered blouse with a richly worked skirt and a scalloped net dupatta.

The blouse is made to measure, with the sleeve length and neckline chosen at your fitting. Please allow 4 to 6 weeks.', array['/images/lookbook/shehzadi-bridal-2.jpg', '/images/lookbook/shehzadi-bridal-1.jpg', '/images/lookbook/shehzadi-bridal-3.jpg']::text[], 'Bride in a red lehenga with gold embroidery and emerald kundan jewellery', array['Made to measure']::text[], array['Bridal Red', 'Gold']::text[], 'Velvet and raw silk', 62000, true, null, true, 'made_to_order', true, 1, true) on conflict (slug) do nothing;
insert into public.products (name, slug, category_id, subcategory, short_description, description, images, image_alt, sizes, colors, fabric, price, is_customizable, customization_notes, stitching_available, availability, is_featured, featured_order, is_visible) values ('Mint Green Wedding Lehenga', 'mint-green-wedding-lehenga', (select id from public.categories where slug = 'wedding-collection'), null, 'Mint lehenga with tonal thread work and a sheer gold-edged dupatta, made for day weddings.', null, array['/images/lookbook/mint-wedding-lehenga.jpg']::text[], 'Woman in a mint green embroidered lehenga with a sheer dupatta', array['S', 'M', 'L', 'XL', 'Custom']::text[], array['Mint Green', 'Gold']::text[], 'Georgette with thread work', 16500, true, null, true, 'in_stock', false, 0, true) on conflict (slug) do nothing;
insert into public.products (name, slug, category_id, subcategory, short_description, description, images, image_alt, sizes, colors, fabric, price, is_customizable, customization_notes, stitching_available, availability, is_featured, featured_order, is_visible) values ('Leheriya Chaniya Choli', 'leheriya-chaniya-choli', (select id from public.categories where slug = 'chaniya-choli'), 'Navratri', 'Red and pink leheriya chaniya with a gota border, made to swirl through every garba round.', null, array['/images/lookbook/leheriya-chaniya-choli.jpg']::text[], 'Woman in a red and pink striped leheriya chaniya choli', array['S', 'M', 'L', 'XL', 'Custom']::text[], array['Red', 'Rani Pink']::text[], 'Cotton silk', 5850, true, null, true, 'in_stock', true, 3, true) on conflict (slug) do nothing;
insert into public.products (name, slug, category_id, subcategory, short_description, description, images, image_alt, sizes, colors, fabric, price, is_customizable, customization_notes, stitching_available, availability, is_featured, featured_order, is_visible) values ('Maroon Embroidered Lehenga Choli', 'maroon-embroidered-lehenga-choli', (select id from public.categories where slug = 'festive-wear'), null, 'Wine-maroon lehenga choli with a fully embroidered crop blouse.', null, array['/images/lookbook/maroon-lehenga-choli.jpg']::text[], 'Woman in a maroon lehenga choli with an embroidered crop blouse', array['S', 'M', 'L', 'XL']::text[], array['Maroon']::text[], 'Silk blend', 14200, true, null, false, 'in_stock', false, 0, true) on conflict (slug) do nothing;
insert into public.products (name, slug, category_id, subcategory, short_description, description, images, image_alt, sizes, colors, fabric, price, is_customizable, customization_notes, stitching_available, availability, is_featured, featured_order, is_visible) values ('Black & Gold Lehenga Choli', 'black-gold-lehenga-choli', (select id from public.categories where slug = 'festive-wear'), null, 'Dramatic black lehenga with antique-gold embroidery, for sangeet and cocktail nights.', null, array['/images/lookbook/black-gold-lehenga.jpg']::text[], 'Woman in a black and gold embroidered lehenga choli', array['S', 'M', 'L']::text[], array['Black', 'Antique Gold']::text[], 'Velvet', 13800, false, null, false, 'in_stock', false, 0, true) on conflict (slug) do nothing;
insert into public.products (name, slug, category_id, subcategory, short_description, description, images, image_alt, sizes, colors, fabric, price, is_customizable, customization_notes, stitching_available, availability, is_featured, featured_order, is_visible) values ('Midnight Navy Pre-Draped Saree', 'midnight-navy-pre-draped-saree', (select id from public.categories where slug = 'festive-wear'), null, 'Ready-to-wear navy saree with a sequinned blouse. It''s on in minutes, elegant all night.', null, array['/images/lookbook/navy-predraped-saree.jpg']::text[], 'Woman in a midnight navy pre-draped saree with a sequinned blouse', array['S', 'M', 'L', 'XL']::text[], array['Navy']::text[], 'Satin georgette', 8900, false, null, false, 'in_stock', false, 0, true) on conflict (slug) do nothing;
insert into public.products (name, slug, category_id, subcategory, short_description, description, images, image_alt, sizes, colors, fabric, price, is_customizable, customization_notes, stitching_available, availability, is_featured, featured_order, is_visible) values ('Emerald Ruffle Saree with Designer Blouse', 'emerald-ruffle-saree-designer-blouse', (select id from public.categories where slug = 'womens-ethnic-wear'), null, 'Emerald ruffle saree with a gold border and an embellished designer blouse.', null, array['/images/lookbook/emerald-ruffle-saree.jpg', '/images/lookbook/emerald-ruffle-saree-back.jpg']::text[], 'Woman in an emerald green ruffle saree with a gold border', '{}'::text[], array['Emerald', 'Gold']::text[], 'Georgette', 9450, false, null, true, 'in_stock', false, 0, true) on conflict (slug) do nothing;
insert into public.products (name, slug, category_id, subcategory, short_description, description, images, image_alt, sizes, colors, fabric, price, is_customizable, customization_notes, stitching_available, availability, is_featured, featured_order, is_visible) values ('Turquoise Zari-Sleeve Blouse', 'turquoise-zari-sleeve-blouse', (select id from public.categories where slug = 'blouses'), 'Designer', 'Turquoise silk blouse with heavy gold zari on the sleeves, made to pair with Kanjeevaram sarees.', null, array['/images/lookbook/turquoise-zari-blouse.jpg']::text[], 'Close-up of a turquoise silk blouse sleeve with gold zari embroidery', array['32', '34', '36', '38', '40', '42', 'Custom']::text[], array['Turquoise', 'Gold']::text[], 'Pure silk', 3950, true, null, true, 'in_stock', true, 2, true) on conflict (slug) do nothing;
insert into public.products (name, slug, category_id, subcategory, short_description, description, images, image_alt, sizes, colors, fabric, price, is_customizable, customization_notes, stitching_available, availability, is_featured, featured_order, is_visible) values ('Navy Velvet Zardozi Blouse', 'navy-velvet-zardozi-blouse', (select id from public.categories where slug = 'antique-blouses'), 'Antique', 'Navy velvet blouse with antique zardozi motifs on the sleeves.', null, array['/images/lookbook/navy-velvet-zardozi-blouse.jpg']::text[], 'Close-up of a navy velvet blouse with antique gold zardozi on the sleeve', array['32', '34', '36', '38', '40', '42', 'Custom']::text[], array['Navy', 'Antique Gold']::text[], 'Velvet', 5250, true, null, true, 'in_stock', false, 0, true) on conflict (slug) do nothing;
insert into public.products (name, slug, category_id, subcategory, short_description, description, images, image_alt, sizes, colors, fabric, price, is_customizable, customization_notes, stitching_available, availability, is_featured, featured_order, is_visible) values ('Red Silk Blouse with Kasavu Saree', 'red-silk-blouse-kasavu-saree', (select id from public.categories where slug = 'blouses'), null, 'Long-sleeve red silk blouse styled with a gold tissue saree.', null, array['/images/lookbook/red-blouse-drape.jpg']::text[], 'Woman in a red long-sleeve silk blouse and gold tissue saree', array['32', '34', '36', '38', '40', '42', 'Custom']::text[], array['Red', 'Gold']::text[], 'Silk', 2750, false, null, true, 'in_stock', false, 0, true) on conflict (slug) do nothing;
insert into public.products (name, slug, category_id, subcategory, short_description, description, images, image_alt, sizes, colors, fabric, price, is_customizable, customization_notes, stitching_available, availability, is_featured, featured_order, is_visible) values ('Royal Blue Embroidered Salwar Suit', 'royal-blue-embroidered-salwar-suit', (select id from public.categories where slug = 'salwar-kameez'), null, 'Royal blue straight suit with dense yoke embroidery and a contrast dupatta.', null, array['/images/lookbook/blue-salwar-suit.jpg']::text[], 'Woman in a royal blue embroidered salwar suit with a beige dupatta', array['S', 'M', 'L', 'XL', 'XXL', 'Custom']::text[], array['Royal Blue']::text[], 'Chanderi silk', 4650, false, null, true, 'in_stock', true, 6, true) on conflict (slug) do nothing;
insert into public.products (name, slug, category_id, subcategory, short_description, description, images, image_alt, sizes, colors, fabric, price, is_customizable, customization_notes, stitching_available, availability, is_featured, featured_order, is_visible) values ('Ivory Block-Print Kurta Set', 'ivory-block-print-kurta-set', (select id from public.categories where slug = 'salwar-kurta'), null, 'Breathable ivory cotton kurta with hand block-printed florals and matching pants.', null, array['/images/lookbook/ivory-kurta-set.jpg']::text[], 'Woman in an ivory floral block-printed kurta and pants', array['S', 'M', 'L', 'XL', 'XXL', 'Custom']::text[], array['Ivory', 'Rose']::text[], 'Cotton', 2450, false, null, true, 'in_stock', false, 0, true) on conflict (slug) do nothing;
insert into public.products (name, slug, category_id, subcategory, short_description, description, images, image_alt, sizes, colors, fabric, price, is_customizable, customization_notes, stitching_available, availability, is_featured, featured_order, is_visible) values ('Girls'' Dandiya Chaniya Choli', 'girls-dandiya-chaniya-choli', (select id from public.categories where slug = 'girls-wear'), null, 'Bright red chaniya choli for little garba stars, light and easy to dance in.', null, array['/images/lookbook/girls-dandiya-chaniya.jpg']::text[], 'Smiling girl in a red chaniya choli holding dandiya sticks', array['4–5 yrs', '6–7 yrs', '8–9 yrs', '10–12 yrs']::text[], array['Red', 'Blue']::text[], 'Cotton silk', 2250, false, null, false, 'in_stock', true, 7, true) on conflict (slug) do nothing;
insert into public.products (name, slug, category_id, subcategory, short_description, description, images, image_alt, sizes, colors, fabric, price, is_customizable, customization_notes, stitching_available, availability, is_featured, featured_order, is_visible) values ('Pearl-Beaded Cape Saree', 'pearl-beaded-cape-saree', (select id from public.categories where slug = 'custom-designs'), 'Couture', 'A custom couture piece: a champagne saree with a hand-beaded cape blouse.', null, array['/images/lookbook/pearl-cape-saree.jpg']::text[], 'Woman in a champagne saree with a hand-beaded cape', array['Made to measure']::text[], array['Champagne']::text[], 'Satin with hand beading', 18500, true, null, true, 'made_to_order', false, 0, true) on conflict (slug) do nothing;
